import { Event } from '@/types/event';

export const MOCK_EVENTS: Event[] = [
  {
    id: 'evt_001',
    name: 'Phoenix Mall Mega Sale',
    description: 'Annual mega sale drawing exceptionally large crowds across all mall zones.',
    venueId: 'v_01',
    venueName: 'Phoenix Mall',
    eventType: 'SHOPPING',
    startTime: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    endTime: new Date(Date.now() + 6 * 60 * 60 * 1000).toISOString(),
    expectedVisitors: 30000,
    status: 'LIVE',
    createdBy: 'usr_admin',
    createdAt: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 1 * 60 * 60 * 1000).toISOString(),
    currentVisitors: 24853,
    riskLevel: '82% HIGH',
  },
  {
    id: 'evt_002',
    name: 'Weekend Concert Series',
    description: 'Outdoor music festival featuring local bands.',
    venueId: 'v_02',
    venueName: 'Central Plaza',
    eventType: 'CONCERT',
    startTime: new Date(Date.now() + 24 * 60 * 60 * 1000).toISOString(),
    endTime: new Date(Date.now() + 28 * 60 * 60 * 1000).toISOString(),
    expectedVisitors: 15000,
    status: 'UPCOMING',
    createdBy: 'usr_events',
    createdAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'evt_003',
    name: 'City Marathon 2026',
    description: 'Annual city marathon spanning across multiple districts.',
    venueId: 'v_03',
    venueName: 'Downtown Circuit',
    eventType: 'SPORTS',
    startTime: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(),
    endTime: new Date(Date.now() - 1 * 60 * 60 * 1000).toISOString(),
    expectedVisitors: 50000,
    status: 'COMPLETED',
    createdBy: 'usr_admin',
    createdAt: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 1 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'evt_004',
    name: 'Tech Innovators Expo',
    description: 'Showcasing the latest in AI and robotics.',
    venueId: 'v_04',
    venueName: 'Convention Center',
    eventType: 'FESTIVAL',
    startTime: new Date(Date.now() + 5 * 24 * 60 * 60 * 1000).toISOString(),
    endTime: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000).toISOString(),
    expectedVisitors: 12000,
    status: 'UPCOMING',
    createdBy: 'usr_events',
    createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'evt_005',
    name: 'Subway Station Overhaul',
    description: 'Major renovation work causing reroutes and crowds.',
    venueId: 'v_05',
    venueName: 'Central Station',
    eventType: 'TRANSPORT',
    startTime: new Date(Date.now() - 10 * 60 * 1000).toISOString(),
    endTime: new Date(Date.now() + 4 * 60 * 60 * 1000).toISOString(),
    expectedVisitors: 8000,
    status: 'STARTING',
    createdBy: 'usr_admin',
    createdAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 15 * 60 * 1000).toISOString(),
    currentVisitors: 540,
    riskLevel: '20% LOW',
  }
];
