"""Add crowd_metrics table

Revision ID: 13780c56bb1e
Revises: 3d4be8b11320
Create Date: 2026-08-21 21:17:20.833935

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '13780c56bb1e'
down_revision: Union[str, Sequence[str], None] = '3d4be8b11320'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crowd_metrics',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('event_id', sa.String(), nullable=False),
    sa.Column('zone_id', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('people_count', sa.Integer(), nullable=False),
    sa.Column('density', sa.Float(), nullable=False),
    sa.Column('occupancy_percentage', sa.Float(), nullable=False),
    sa.Column('average_speed', sa.Float(), nullable=False),
    sa.Column('entry_rate', sa.Float(), nullable=False),
    sa.Column('exit_rate', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['zone_id'], ['zones.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crowd_metrics_event_id'), 'crowd_metrics', ['event_id'], unique=False)
    op.create_index(op.f('ix_crowd_metrics_timestamp'), 'crowd_metrics', ['timestamp'], unique=False)
    op.create_index(op.f('ix_crowd_metrics_zone_id'), 'crowd_metrics', ['zone_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_crowd_metrics_zone_id'), table_name='crowd_metrics')
    op.drop_index(op.f('ix_crowd_metrics_timestamp'), table_name='crowd_metrics')
    op.drop_index(op.f('ix_crowd_metrics_event_id'), table_name='crowd_metrics')
    op.drop_table('crowd_metrics')
    # ### end Alembic commands ###
