"""Add event infrastructure tables

Revision ID: b4c63bfbaef5
Revises: 2af989563748
Create Date: 2026-08-21 17:01:01.234246

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b4c63bfbaef5'
down_revision: Union[str, Sequence[str], None] = '2af989563748'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_gates',
    sa.Column('event_id', sa.String(), nullable=False),
    sa.Column('gate_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['gate_id'], ['gates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('event_id', 'gate_id')
    )
    op.create_table('event_zones',
    sa.Column('event_id', sa.String(), nullable=False),
    sa.Column('zone_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['zone_id'], ['zones.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('event_id', 'zone_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('event_zones')
    op.drop_table('event_gates')
    # ### end Alembic commands ###
