"""Add new audit_log columns

Revision ID: e52039e7c736
Revises: f2b234af546b
Create Date: 2026-08-23 02:51:04.646283

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e52039e7c736'
down_revision: Union[str, Sequence[str], None] = 'f2b234af546b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audit_logs', sa.Column('event_id', sa.String(), nullable=True))
    op.add_column('audit_logs', sa.Column('target_type', sa.String(), nullable=True))
    op.add_column('audit_logs', sa.Column('result', sa.String(), nullable=True))
    op.add_column('audit_logs', sa.Column('metadata', sa.JSON(), nullable=True))
    op.add_column('audit_logs', sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False))
    op.create_index(op.f('ix_audit_logs_event_id'), 'audit_logs', ['event_id'], unique=False)
    op.create_foreign_key(None, 'audit_logs', 'events', ['event_id'], ['id'], ondelete='CASCADE')
    op.drop_column('audit_logs', 'created_at')
    op.drop_column('audit_logs', 'details')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audit_logs', sa.Column('details', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('audit_logs', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'audit_logs', type_='foreignkey')
    op.drop_index(op.f('ix_audit_logs_event_id'), table_name='audit_logs')
    op.drop_column('audit_logs', 'timestamp')
    op.drop_column('audit_logs', 'metadata')
    op.drop_column('audit_logs', 'result')
    op.drop_column('audit_logs', 'target_type')
    op.drop_column('audit_logs', 'event_id')
    # ### end Alembic commands ###
