"""Add Gate model

Revision ID: f927937872aa
Revises: fd8acaf4ae83
Create Date: 2026-08-21 16:24:05.616060

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f927937872aa'
down_revision: Union[str, Sequence[str], None] = 'fd8acaf4ae83'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gates',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('venue_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('gate_number', sa.String(), nullable=False),
    sa.Column('type', sa.Enum('ENTRY', 'EXIT', 'EMERGENCY', 'SERVICE', name='gatetype'), nullable=False),
    sa.Column('capacity_per_hour', sa.Integer(), nullable=False),
    sa.Column('location', sa.JSON(), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'CLOSED', 'MAINTENANCE', name='gatestatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['venue_id'], ['venues.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('gates')
    # ### end Alembic commands ###
