"""Add Zone model

Revision ID: fd8acaf4ae83
Revises: 7c93bd18272f
Create Date: 2026-08-21 15:54:21.500540

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fd8acaf4ae83'
down_revision: Union[str, Sequence[str], None] = '7c93bd18272f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('zones',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('venue_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('area', sa.Float(), nullable=True),
    sa.Column('boundary', sa.JSON(), nullable=False),
    sa.Column('warning_density', sa.Float(), nullable=False),
    sa.Column('high_density', sa.Float(), nullable=False),
    sa.Column('critical_density', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['venue_id'], ['venues.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('zones')
    # ### end Alembic commands ###
